.\" Copyright (C) 2024 Casey Schaufler <casey@schaufler-ca.com>
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH lsm_list_modules 1 (date) "Linux man-pages (unreleased)"
.SH NAME
lsm_list_modules \- list active Linux Security Modules (LSM)
.SH SYNOPSIS
.B lsm_list_modules
.SH DESCRIPTION
The
.B lsm_list_modules
program prints a comma separated list of the Linux Security Modules (LSM)
that are active on the system.
.SH SEE ALSO
.BR lsm_list_modules (2)
